import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import '../styles/index.css';
import '../styles/app.scss';


function App({ Component, pageProps }){
  return (
    <>
      <Head>
        <title>Funiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*<Header/>*/}
      <Component {...pageProps} />
      {/*<Footer/>*/}
    </>
    )

}

export default App
